apiVersion: v1
kind: Service
metadata:
  name: crate-db
  labels:
    app: fiware

spec:
  selector:
    app: crate-db
    
  ports:
  - name: "4200"
    port: 4200
    targetPort: 4200
  - name: "4300"
    port: 4300
    targetPort: 4300